import { createElement } from 'lwc';
import Pricing_CheckerViewComp from 'c/pricing_CheckerViewComp';

describe('c-pricing-checker-view-comp', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-pricing-checker-view-comp', {
            is: Pricing_CheckerViewComp
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});