public class MerchantAADetailsTriggerHandler {

    public static void beforeInsertHandler(List<Merchant_Auto_Approval_Details__c> triggerNew){}
    
    public static void beforeUpdateHandler(List<Merchant_Auto_Approval_Details__c> triggerNew, Map<Id, Merchant_Auto_Approval_Details__c> triggerOldMap){}
    
    public static void afterInsertHandler(List<Merchant_Auto_Approval_Details__c> triggerNew){}
    
    public static void afterUpdateHandler(List<Merchant_Auto_Approval_Details__c> triggerNew, Map<Id, Merchant_Auto_Approval_Details__c> triggerOldMap){}
}